apiVersion: v1
kind: ServiceAccount
metadata:
  name: my-pod-sa
  namespace: default
  annotations:
    # This annotation will be added by the gcloud command
    iam.gke.io/gcp-service-account: gcs-access-sa@YOUR-PROJECT-ID.iam.gserviceaccount.com
